/*
 *  Copyright 2018 Mike Reed
 */

#include "GCanvas.h"
#include "GShader.h"

std::unique_ptr<GShader> GCanvas::final_createRadialGradient(GPoint center, float radius,
                                                             const GColor colors[], int count) {
    // DO NOT EDIT THIS FILE
    // override this method in your canvas subclass, and implement it there.
    return nullptr;
}

void GCanvas::final_addStrokedLine(GPath* path, GPoint p0, GPoint p1, float width, bool roundCap) {
    // DO NOT EDIT THIS FILE
    // override this method in your canvas subclass, and implement it there.
}

std::unique_ptr<GShader> GCanvas::final_createTriangleGradient(const GPoint pts[3],
                                                               const GColor colors[3]) {
    // DO NOT EDIT THIS FILE
    // override this method in your canvas subclass, and implement it there.
    return nullptr;
}
